version: '3.7'
services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: challenge3
      POSTGRES_USER: root
      POSTGRES_PASSWORD: compass
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: