POST http://localhost:3001/categories HTTP/1.1
Content-Type: application/json

{   
    "name" : "living",
    "image_link": "https://i.postimg.cc/MTJY8N15/quarto.png"
}   

###

GET http://localhost:3001/categories HTTP/1.1
###

GET http://localhost:3001/categories/2 HTTP/1.1

### GEt All Products by category

GET http://localhost:3001/categories/Bedroom HTTP/1.1
