POST http://localhost:3000/categories HTTP/1.1
Content-Type: application/json

{
    "name" : "Bedroom",
    "image_link": "https://postimg.cc/MTJY8N15"
}   

###

GET http://localhost:3000/categories HTTP/1.1

### GEt All Products by category

GET http://localhost:3000/categories/Bedroo HTTP/1.1
