
//Regiter a product
POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
    "name": "Sofa",
    "sku": "SOFA1B002",
    "description" : "Dois Lugares",
    "category_id" : 1,
    "tags" : ["a"],
    "large_description" : "Sofa lindo dois lugares top de linha",
    "large_description2" : "Large Description 2",
    "additional_information" : "Additional information",
    "price": 10000,
    "discount_price": 8000,
    "discount_percent" : 20,
    "is_new" : true,
    "image_link" : "https://postimg.cc/v4rfB85z",
    "other_images_link" : "https://postimg.cc/v4rfB85z"
}

###df
//Get all products
GET http://localhost:3000/products HTTP/1.1