
//Regiter a product
POST http://localhost:3001/products HTTP/1.1
Content-Type: application/json

{
    "name": "teste5645",
    "sku": "SOFA1B002",
    "description" : "outra pagina",
    "category_id" : 10 ,
    "tags" : ["a", "b"],
    "large_description" : "Sofa lindo dois lugares top de linha",
    "large_description2" : "Large Description 2",
    "additional_information" : "Additional information",
    "price": 10000,
    "discount_price": 8000,
    "discount_percent" : 20,
    "is_new" : true,
    "image_link" : "https://postimg.cc/v4rfB85z",
    "other_images_link" : "https://postimg.cc/v4rfB85z"
}

###
//Get all products
GET http://localhost:3001/products?page=1&limit=2 HTTP/1.1


### Get a expecific amount 
GET http://localhost:3001/products/?amount=2 HTTP/1.1

### Get by category
GET http://localhost:3001/products/category?name=living&page=1&limit=2 HTTP/1.1


### Get one product

GET http://localhost:3001/products/3d89e527-c298-430f-8c14-a17db8811883 HTTP/1.1


